Examen2194309/Models/Article.cs
namespace Examen2194309.Models
{
    public class Article
    {
        public int Id { get; set; } 
        public string Nom { get; set; }


        public Article(int id, string nom)
        {
            Id = id;
            Nom = nom;
        }
    }
}

Examen2194309/Controllers/AcceuilController.cs
using Microsoft.AspNetCore.Mvc;

namespace Examen2194309.Controllers
{
    public class AcceuilController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Examen2194309/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Examen2194309.Models;

namespace Examen2194309.Controllers
{
    public class ArticleController : Controller
    {
        private readonly List<Article> _articles;
        public ArticleController()
        {
            _articles = new List<Article>()
            {
                // TODO: les noms de tes articles ne sont pas supposés être les mêmes. 
                //       Je comprend que tu t'en serves pour les afficher facilement 
                //       dans une vue mais ce n'est pas bon. 
                //       Tu as contourné le problème en arrangeant les données à ton programme, 
                //       mais c'est un peu de la triche. Tu devrais penser à une structure de 
                //       données différente qui te permettre de résoudre le vrai problème réél.
                new Article(0, "Sport"),
                new Article(1, "Sport"),
                new Article(2, "Sport"),
                new Article(3, "Sport"),
                new Article(4, "Jeu"),
                new Article(5, "Jeu"),
                new Article(6, "Jeu"),
                new Article(7, "Jeu"),
                new Article(8, "Outil"),
                new Article(9, "Outil"),
                new Article(10, "Outil"),
                new Article(11, "Outil"),
                new Article(12, "Vetements"),
                new Article(13, "Vetements"),
                new Article(14, "Vetements"),
                new Article(15, "Vetements"),
            };
        }

        // TODO: Cette méthode d'action ne devrait pas exister, 
        //       tu devais réutiliser la méthode d'action Souhaits.
        public ViewResult TotalSouhaits()
        {

            ViewBag.Titre = "Tout les souhaits";

            return View(_articles);
        }


        public ViewResult MesSouhaits()
        {

            ViewBag.Titre = "Mes listes de souhaits";

            // TODO: Tu devais envoyer les donnes (liste des souhaits) 
            //       à ta vue à partir d'ici (ton contrôleur). 
            return View("MesSouhaits");
        }


        // TODO: Tu devais réutiliser cette méthode pour
        //       afficher la liste de tous les articles.
        public ViewResult Souhaits(int id)
        {
            // TODO: Tu te sert du nom de l'article pour 
            //      sélectionner les articles à afficher. 
            //      Ta solution ne fonctionnera pas en 
            //      réalité car les noms des articles 
            //      ne sont pas supposés être les mêmes.
            int idArticle = _articles.FindIndex(i => i.Id == id);

            string nomArticle = _articles[idArticle].Nom;

            ViewBag.Titre = "Souhaits de la liste choisie";
            ViewData["nomArticle"] = nomArticle;

            return View(_articles);
        }
    }
}

Examen2194309/Views/Acceuil/Index.cshtml
@{
    ViewData["TitrePage"] = "Page d'acceuil";
    ViewData["Titre"] = "Un Titre";
    ViewData["Description"] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["TitrePage"]</title>
</head>
<body>
    <h1>@ViewData["Titre"]</h1>

    <h2>
        @ViewData["Description"]
    </h2>

    <ul>
        <li><a asp-controller="Article" asp-action="TotalSouhaits">Voir mes listes de Souhaits</a></li>
        <li><a asp-controller="Article" asp-action="MesSouhaits">Voir Tous mes Souhaits</a></li>
    </ul>
</body>

Examen2194309/Views/Article/MesSouhaits.cshtml
@model List<Examen2194309.Models.Article>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>@ViewData["Titre"]</title>
</head>
<body>
     <h1>@ViewData["Titre"]</h1>
     <ul>
            <li><a asp-controller="Article" asp-action="Souhaits" asp-route-id=0>Voir les articles de Pc et Jeux</a></li>
             <li><a asp-controller="Article" asp-action="Souhaits" asp-route-id=4>Voir les articles de Sports</a></li>
             <li><a asp-controller="Article" asp-action="Souhaits" asp-route-id=8>Voir les articles de Fourniture</a></li>
             <li><a asp-controller="Article" asp-action="Souhaits" asp-route-id=12>Voir les articles de Vetements</a></li>
    </ul>
</body>
<html>

Examen2194309/Views/Article/Souhaits.cshtml
@model List<Examen2194309.Models.Article>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>@ViewData["Titre"]</title>
</head>
<body>
     <h1 >@ViewData["Titre"]</h1>
     <div>
        @foreach (var article in Model)
        {
            if (article.Nom == @ViewData["nomArticle"])
            {
                <h3>@article.Id,@ViewData["nomArticle"]</h3>
            }
        }
     </div>
</body>
</html>

Examen2194309/Views/Article/TotalSouhaits.cshtml
@model List<Examen2194309.Models.Article>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>@ViewData["Titre"]</title>
</head>
<body>
     <h1>@ViewData["Titre"]</h1>
     <div>
        @foreach (var article in Model)
        {
            <h3>@article.Id, @article.Nom</h3>
        }
     </div>
</body>
</html>